### ISSUE TITLE
Update plugin for Netbeans 7

### ISSUE THREAD

**Issue by Forage** [carbonfx/netbeans-valaproject#1]
Hi,

First of all: thanks for adding Vala support to Netbeans! At least this prevents my to use a different editor just for one language, like I'm already forced to do because of C#.

When I try to install the plugin I get the following error:
"The plugin named Editor Library is needed and not found"

I assume this is because the plugin is for Netbeans 6.9 and not for 7.
Are there any plans to update the plugin for Netbeans 7?

Yours,

**Comment by senz** [comment]
Hello, atm plugin is not maintained due to lack of time and switch to scala.
We'll try to figure something out if we can. Thanks

**Comment by senz** [comment]
Btw, there is branch for nb 7, can you try to compile it and run?

**Comment by Forage** [comment]
With a big delay:

So far I managed to do the bits of Vala in gedit but it is getting more complicated.
There is indeed a nb7 branch, overlooked that one earlier. How should a netbeans plugin be compiled in order to test it?

**Comment by maqdev** [comment]
Sorry, this project is discontinued.
