### ISSUE TITLE
Download section wrong link

### ISSUE THREAD

**Issue by anatooly** [carbonfx/netbeans-valaproject#2]
Uncorrect link: https://github.com/carbonfx/netbeans-valaproject/blob/master/netbeans-valaproject/downloads on you "Download and Install" section.

**Comment by yhjhoo** [comment]
I am have the same issue. How to use this plugin?

**Comment by maqdev** [comment]
Files are here: https://github.com/carbonfx/netbeans-valaproject/downloads
But this project is discontinued, i don't know if these packages are working with any recent version of netbeans

**Comment by yhjhoo** [comment]
oops, if doesn't work in netbean 7.4

Got this error:
Some plugins require plugin Editor Library to be installed.
The plugin named Editor Library is needed and not found.  The following plugin is affected:       Vala Project
